site_name: Фриланс биржа "Outlance"
nav:
  - Home: index.md
  - Api:
      - Portfolio:
          - "Проверка портфолио": portfolio/check.md
      - Order:
          - "Создание заказа": portfolio/check.md

theme:
  name: material