site_name: Фриланс биржа "Outlance"
nav:
  - Home: index.md
  - Api:
      - Portfolio:
          - "Проверка портфолио": portfolio/check.md
      - Order:
          - "Создание и просмотр заказов": order/order.md
          - "Загрузка файлов в заказ, правки, результаты": order/files.md
          - "Работа исполнителя с заказом": order/oreder_review.md
          - "Работа с правкам": order/order_result.md
      - Messenger:
          - "Работа с чатом": messenger/join_to_chat.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust